2021-07-07 00:09:13.694226: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "runMotor.py", line 11, in <module>
    faulthandler.enable(file="./fault_dump")
AttributeError: 'str' object has no attribute 'fileno'
